---
######################################################
# Default Configuration
######################################################
spring:
  profiles:
    default: local-postgres
  docker:
    compose:
      enabled: false

api:
  airport:
    username: ${AIRPORT_API_USERNAME}
    password: ${AIRPORT_API_PASSWORD}
    url: ${AIRPORT_API_URL}
  weather:
    url: ${WEATHER_API_URL}

springdoc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    api-docs:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
---
######################################################
# Local Configuration (Postgres & Docker)
######################################################
spring:
  config:
    activate:
      on-profile: local-postgres
  datasource:
    url: jdbc:postgresql://localhost:55432/airport_service_db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  docker:
    compose:
      file: ./compose.yml
      enabled: true
---
######################################################
# Dev/Staging Configuration
######################################################
spring:
  config:
    activate:
      on-profile: dev, staging
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
######################################################
# Review App Configuration (For Pull Requests)
######################################################
spring:
  config:
    activate:
      on-profile: review
  datasource:
    url: jdbc:h2:mem:airport_service_db
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
