---
######################################################
# Default Configuration
######################################################
spring:
  profiles:
    default: local-postgres

api:
  airport:
    username: ${AIRPORT_API_USERNAME}
    password: ${AIRPORT_API_PASSWORD}
    url: ${AIRPORT_API_URL}
  weather:
    url: ${WEATHER_API_URL}

springdoc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
    api-docs:
      enabled: true
---
######################################################
# Local Configuration (Postgres & Docker)
######################################################
#spring:
#  config:
#    activate:
#      on-profile: local-postgres
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:55432/airport_service_db
#    username: postgres
#    password: postgres
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  docker:
#    compose:
#      file: ./compose.yml
#      enabled: true

---
######################################################
# Local Configuration (H2)
######################################################
#spring:
#  config:
#    activate:
#      on-profile: local-h2
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:airport_service_db
#    username: root
#    password: root
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  docker:
#    compose:
#      enabled: false
