services:
  db:
    container_name: airport-service-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airport_service_db
    ports:
      - 55432:5432
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
